export type Domain = {
  id: string
  nameEn: string
  nameZh: string
  modules: string[]
  progress: number
  active?: boolean
}

export type GraphNode = {
  id: string
  label: string
  domain: string
  mastery: string
  summary: string
  connections: string[]
}

export const domains: Domain[] = [
  {
    id: 'META',
    nameEn: 'META',
    nameZh: '元能力',
    progress: 84,
    active: true,
    modules: [
      'Systems Thinking（系统思维）',
      'Causal Reasoning（因果推理）',
      'Probability（概率）',
      'Bayesian Thinking（贝叶斯思维）',
      'Source Evaluation（信息源评估）',
      'Forecasting（预测）',
    ],
  },
  {
    id: 'SELF',
    nameEn: 'SELF',
    nameZh: '自我',
    progress: 0,
    modules: ['Cognition（认知）', 'Learning（学习）', 'Decision Making（决策）', 'Life Systems（人生系统）'],
  },
  {
    id: 'HUMAN',
    nameEn: 'HUMAN',
    nameZh: '人',
    progress: 0,
    modules: ['Psychology（心理学）', 'Behavioral Economics（行为经济学）', 'Social Dynamics（社会动力学）'],
  },
  {
    id: 'CIVILIZATION',
    nameEn: 'CIVILIZATION',
    nameZh: '文明',
    progress: 0,
    modules: ['Human Civilization（人类文明）', 'China（中国）', 'United States（美国）', 'World Order（世界秩序）'],
  },
  {
    id: 'SYSTEM',
    nameEn: 'SYSTEM',
    nameZh: '现代社会系统',
    progress: 0,
    modules: ['Economics（经济学）', 'Finance（金融）', 'Politics（政治）', 'Geopolitics（地缘政治）'],
  },
  {
    id: 'BUSINESS',
    nameEn: 'BUSINESS',
    nameZh: '商业',
    progress: 68,
    active: true,
    modules: ['Business Fundamentals（商业基础）', 'Industry Atlas（产业图谱）'],
  },
  {
    id: 'SCIENCE',
    nameEn: 'SCIENCE',
    nameZh: '科学',
    progress: 0,
    modules: ['Mathematics & Statistics（数学与统计）', 'Physics（物理）', 'Biology（生物学）'],
  },
  {
    id: 'FRONTIER',
    nameEn: 'FRONTIER',
    nameZh: '科技前沿',
    progress: 0,
    modules: ['Artificial Intelligence（人工智能）', 'AI Infrastructure（人工智能基础设施）', 'Robotics（机器人）'],
  },
  {
    id: 'WISDOM',
    nameEn: 'WISDOM',
    nameZh: '智慧',
    progress: 0,
    modules: ['Philosophy（哲学）', 'Intellectual Traditions（思想传统）', 'Art & Humanity（艺术与人文）'],
  },
]

export const nodes: GraphNode[] = [
  {
    id: 'META.SYSTEMS.SYSTEM',
    label: 'System（系统）',
    domain: 'META',
    mastery: 'L1 candidate',
    summary: 'The parent frame for understanding how relationships among parts produce behavior that cannot be inferred from a parts list.',
    connections: ['META.SYSTEMS.INTERDEPENDENCE', 'META.SYSTEMS.COUPLING', 'BUS.MEDIA.PAYTV.VALUE_CHAIN'],
  },
  {
    id: 'META.SYSTEMS.INTERDEPENDENCE',
    label: 'Interdependence（相互依赖）',
    domain: 'META',
    mastery: 'L2 candidate',
    summary: 'A part can perform only when other parts align in time, location, state, and constraints. Local health therefore does not guarantee system capability.',
    connections: ['META.SYSTEMS.SYSTEM', 'META.SYSTEMS.COUPLING', 'CASE.SOUTHWEST.2022_MELTDOWN', 'BUS.MEDIA.PAYTV.VALUE_CHAIN'],
  },
  {
    id: 'META.SYSTEMS.COUPLING',
    label: 'Coupling（耦合）',
    domain: 'META',
    mastery: 'L2 candidate',
    summary: 'A local state change alters the conditions faced by connected parts. Connections can share capacity in normal times and transmit disturbance when margins or controls fail.',
    connections: ['META.SYSTEMS.SYSTEM', 'META.SYSTEMS.INTERDEPENDENCE', 'META.SYSTEMS.FEEDBACK_LOOP', 'CASE.NORTHEAST_BLACKOUT.2003', 'BUS.MEDIA.DISTRIBUTOR.DIRECTV'],
  },
  {
    id: 'META.SYSTEMS.FEEDBACK_LOOP',
    label: 'Feedback Loop（反馈回路）',
    domain: 'META',
    mastery: 'L2 candidate',
    summary: 'A system result returns through a causal path to alter its starting condition, either reinforcing the original direction or balancing a deviation.',
    connections: ['META.SYSTEMS.COUPLING', 'META.SYSTEMS.NONLINEARITY', 'META.SYSTEMS.DELAY', 'CASE.SVB.2023_BANK_RUN', 'BUS.SUBSCRIPTION.BUNDLE'],
  },
  {
    id: 'META.SYSTEMS.NONLINEARITY',
    label: 'Nonlinearity（非线性）',
    domain: 'META',
    mastery: 'L2 candidate',
    summary: 'Equal input changes need not produce equal output changes. Near a functional boundary, a small additional step can switch a system from operating to failure.',
    connections: ['META.SYSTEMS.FEEDBACK_LOOP', 'META.SYSTEMS.BOTTLENECK', 'CASE.CHALLENGER.1986', 'BUS.MEDIA.ESPN.BUNDLE_POWER'],
  },
  {
    id: 'META.SYSTEMS.BOTTLENECK',
    label: 'Bottleneck（瓶颈）',
    domain: 'META',
    mastery: 'L2 candidate',
    summary: 'The current constraint whose marginal effective capacity most limits whole-system throughput. Improving a non-bottleneck creates queues; relieving it moves the constraint.',
    connections: ['META.SYSTEMS.NONLINEARITY', 'META.SYSTEMS.DELAY', 'CASE.TESLA.MODEL3_RAMP.2017_2018', 'BUS.MEDIA.CORD_CUTTING.SYSTEM_EFFECT'],
  },
  {
    id: 'META.SYSTEMS.DELAY',
    label: 'Delay（延迟）',
    domain: 'META',
    mastery: 'L2 candidate',
    summary: 'Cause, intervention, and observable outcome are separated in time. Current results can therefore reflect past inputs, making premature adjustment prone to misdiagnosis and overshoot.',
    connections: ['META.SYSTEMS.FEEDBACK_LOOP', 'META.SYSTEMS.BOTTLENECK', 'META.SYSTEMS.INTEGRATION', 'CASE.MONTREAL_PROTOCOL.OZONE_RECOVERY'],
  },
  {
    id: 'META.SYSTEMS.INTEGRATION',
    label: 'Systems Integration（系统整合）',
    domain: 'META',
    mastery: 'L2 candidate',
    summary: 'Start with a whole-system outcome, then follow one necessary unit through dependencies, propagation, returning effects, boundaries, constraints, and delays to locate a real lever.',
    connections: ['META.SYSTEMS.SYSTEM', 'META.SYSTEMS.INTERDEPENDENCE', 'META.SYSTEMS.COUPLING', 'META.SYSTEMS.FEEDBACK_LOOP', 'META.SYSTEMS.NONLINEARITY', 'META.SYSTEMS.BOTTLENECK', 'META.SYSTEMS.DELAY', 'META.CAUSAL.CORRELATION_CAUSATION', 'CASE.AUTOMOTIVE_SEMICONDUCTOR_SHORTAGE.2020_2022'],
  },
  {
    id: 'META.CAUSAL.CORRELATION_CAUSATION',
    label: 'Correlation & Causation（相关与因果）',
    domain: 'META',
    mastery: 'L2 candidate',
    summary: 'Correlation is a symmetric observation of co-movement; causation is a directional intervention claim. Temporal order and reverse paths must be tested before treating a predictor as a lever.',
    connections: ['META.SYSTEMS.INTEGRATION', 'META.CAUSAL.CONFOUNDER', 'META.CAUSAL.INTEGRATION', 'CASE.SMOKING_LUNG_CANCER.CAUSAL_INFERENCE_1950_2004'],
  },
  {
    id: 'META.CAUSAL.CONFOUNDER',
    label: 'Confounder（混杂因素）',
    domain: 'META',
    mastery: 'L2 candidate',
    summary: 'A pre-treatment common cause changes both treatment selection and outcome risk, so an observed group difference can mix the intervention effect with a difference that existed before treatment.',
    connections: ['META.CAUSAL.CORRELATION_CAUSATION', 'META.CAUSAL.COUNTERFACTUAL', 'META.CAUSAL.INTEGRATION', 'CASE.WHI.HORMONE_THERAPY.1991_2002'],
  },
  {
    id: 'META.CAUSAL.COUNTERFACTUAL',
    label: 'Counterfactual（反事实）',
    domain: 'META',
    mastery: 'L2 candidate',
    summary: 'The causal target contrasts two potential outcomes for the same unit at the same time, although only one is observable; a justified comparison group estimates the missing outcome on average.',
    connections: ['META.CAUSAL.CORRELATION_CAUSATION', 'META.CAUSAL.CONFOUNDER', 'META.CAUSAL.SELECTION_BIAS', 'META.CAUSAL.INTEGRATION', 'CASE.OREGON.MEDICAID.LOTTERY.2008_2013'],
  },
  {
    id: 'META.CAUSAL.SELECTION_BIAS',
    label: 'Selection Bias（选择偏差）',
    domain: 'META',
    mastery: 'L2 candidate',
    summary: 'Observed data become systematically unrepresentative when entry or retention depends on causes or outcomes under study; survivorship bias is the special case requiring persistence or visible success.',
    connections: ['META.CAUSAL.CONFOUNDER', 'META.CAUSAL.COUNTERFACTUAL', 'META.CAUSAL.INTEGRATION', 'BUS.SUBSCRIPTION.CHURN_RETENTION', 'CASE.WALD.AIRCRAFT.SURVIVORSHIP.1943'],
  },
  {
    id: 'META.CAUSAL.INTEGRATION',
    label: 'Causal Integration（因果整合）',
    domain: 'META',
    mastery: 'L2 candidate',
    summary: 'Define the intervention and missing counterfactual, then audit direction, treatment assignment, observation gates, and the exact effect the resulting comparison can identify.',
    connections: ['META.CAUSAL.CORRELATION_CAUSATION', 'META.CAUSAL.CONFOUNDER', 'META.CAUSAL.COUNTERFACTUAL', 'META.CAUSAL.SELECTION_BIAS', 'META.PROBABILITY.FOUNDATION', 'CASE.SALK.POLIO_VACCINE_FIELD_TRIAL.1954'],
  },
  {
    id: 'META.PROBABILITY.FOUNDATION',
    label: 'Probability Foundation（概率基础）',
    domain: 'META',
    mastery: 'L2 candidate',
    summary: 'Probability quantifies uncertainty about a defined event under a stated horizon, information set and model; evidence can change the distribution even when the underlying event does not change.',
    connections: ['META.CAUSAL.INTEGRATION', 'META.PROBABILITY.BASE_RATE', 'META.PROBABILITY.CONDITIONAL', 'META.BAYESIAN.UPDATING', 'META.FORECASTING.CALIBRATION', 'BUS.SUBSCRIPTION.LTV', 'CASE.APOPHIS.IMPACT_PROBABILITY.2004_2021'],
  },
  {
    id: 'META.PROBABILITY.BASE_RATE',
    label: 'Base Rate（基础概率）',
    domain: 'META',
    mastery: 'L2 candidate',
    summary: 'A base rate is the target event\'s prevalence in a relevant reference class before case-specific evidence; low prevalence lets a small false-positive rate create more alerts than true detections.',
    connections: ['META.PROBABILITY.FOUNDATION', 'META.PROBABILITY.CONDITIONAL', 'META.BAYESIAN.UPDATING', 'META.CAUSAL.SELECTION_BIAS', 'BUS.SUBSCRIPTION.PRICING_PACKAGING', 'CASE.WISCONSIN.CAMPUS_ANTIGEN_SCREENING.2020'],
  },
  {
    id: 'META.PROBABILITY.CONDITIONAL',
    label: 'Conditional Probability（条件概率）',
    domain: 'META',
    mastery: 'L2 candidate',
    summary: 'Conditional probability recalculates an event within the subpopulation selected by a stated condition; changing or reversing the condition changes the denominator, question and usually the answer.',
    connections: ['META.PROBABILITY.FOUNDATION', 'META.PROBABILITY.BASE_RATE', 'META.BAYESIAN.UPDATING', 'META.CAUSAL.SELECTION_BIAS', 'META.CAUSAL.CONFOUNDER', 'META.FORECASTING.CALIBRATION', 'BUS.MEDIA.AD_SUPPORTED_STREAMING', 'CASE.UC_BERKELEY.ADMISSIONS.1973'],
  },
  {
    id: 'META.BAYESIAN.UPDATING',
    label: 'Bayesian Updating（贝叶斯更新）',
    domain: 'META',
    mastery: 'L2 candidate',
    summary: 'Start from a prior and reallocate probability according to how likely the evidence was under competing hypotheses; more discriminating evidence produces a larger update.',
    connections: ['META.PROBABILITY.FOUNDATION', 'META.PROBABILITY.BASE_RATE', 'META.PROBABILITY.CONDITIONAL', 'META.PROBABILITY.EXPECTED_VALUE', 'META.FORECASTING.CALIBRATION', 'META.CAUSAL.INTEGRATION', 'BUS.MEDIA.REAGGREGATION', 'CASE.AF447.SEARCH.2009_2011'],
  },
  {
    id: 'META.PROBABILITY.EXPECTED_VALUE',
    label: 'Expected Value（期望值）',
    domain: 'META',
    mastery: 'L2 candidate',
    summary: 'Compare actions before uncertainty resolves by multiplying each mutually exclusive outcome probability by its value; one lucky or unlucky realization does not determine decision quality.',
    connections: ['META.PROBABILITY.FOUNDATION', 'META.BAYESIAN.UPDATING', 'META.FORECASTING.CALIBRATION', 'META.CAUSAL.INTEGRATION', 'BUS.SUBSCRIPTION.LTV', 'BUS.MEDIA.DEVICE_OS_POWER', 'CASE.CDC.ACIP.MRNA_BENEFIT_RISK.2021'],
  },
  {
    id: 'CASE.SMOKING_LUNG_CANCER.CAUSAL_INFERENCE_1950_2004',
    label: 'Smoking & Lung Cancer（吸烟与肺癌）',
    domain: 'META',
    mastery: 'Case studied',
    summary: 'Case-control association, prospective timing, dose and cessation patterns, replication, and mechanism progressively constrained reverse-causality explanations without an unethical smoking trial.',
    connections: ['META.CAUSAL.CORRELATION_CAUSATION'],
  },
  {
    id: 'CASE.WHI.HORMONE_THERAPY.1991_2002',
    label: 'WHI Hormone Therapy（WHI 激素治疗）',
    domain: 'META',
    mastery: 'Case studied',
    summary: 'Observational treatment selection could mix baseline health with treatment effects; randomization improved comparability while formulation, age, timing, and adherence still bounded direct study comparison.',
    connections: ['META.CAUSAL.CONFOUNDER'],
  },
  {
    id: 'CASE.OREGON.MEDICAID.LOTTERY.2008_2013',
    label: 'Oregon Medicaid Lottery（医疗补助抽签）',
    domain: 'META',
    mastery: 'Case studied',
    summary: 'A random opportunity to apply created a credible counterfactual for the offer effect, while actual coverage effects required the lottery-induced take-up difference and additional assumptions.',
    connections: ['META.CAUSAL.COUNTERFACTUAL'],
  },
  {
    id: 'CASE.WALD.AIRCRAFT.SURVIVORSHIP.1943',
    label: 'Wald Aircraft Survivorship（返航飞机选择）',
    domain: 'META',
    mastery: 'Case studied',
    summary: 'Returning-plane damage is conditional on survival; Wald modeled location-specific vulnerability from survivor-selected data instead of ranking armor by visible hit counts.',
    connections: ['META.CAUSAL.SELECTION_BIAS'],
  },
  {
    id: 'CASE.SALK.POLIO_VACCINE_FIELD_TRIAL.1954',
    label: 'Salk Polio Trial 1954（脊灰疫苗试验）',
    domain: 'META',
    mastery: 'Case studied',
    summary: 'Randomized placebo recipients supplied a credible counterfactual among consenters; the lower disease rate among uninoculated nonparticipants exposed why untreated groups are not automatically comparable.',
    connections: ['META.CAUSAL.INTEGRATION'],
  },
  {
    id: 'CASE.APOPHIS.IMPACT_PROBABILITY.2004_2021',
    label: 'Apophis Impact Probability（阿波菲斯撞击概率）',
    domain: 'META',
    mastery: 'Case studied',
    summary: 'Limited 2004 observations briefly assigned 2.7% probability to a 2029 impact; archival images and radar narrowed and shifted the allowed orbit distribution until impact was excluded for at least 100 years.',
    connections: ['META.PROBABILITY.FOUNDATION'],
  },
  {
    id: 'CASE.WISCONSIN.CAMPUS_ANTIGEN_SCREENING.2020',
    label: 'Wisconsin Campus Screening（校园抗原筛查）',
    domain: 'META',
    mastery: 'Case studied',
    summary: 'With a 2% asymptomatic base rate, seven true-positive and fourteen false-positive antigen results produced 33.3% PPV despite 98.4% specificity.',
    connections: ['META.PROBABILITY.BASE_RATE'],
  },
  {
    id: 'CASE.UC_BERKELEY.ADMISSIONS.1973',
    label: 'UC Berkeley Admissions 1973（伯克利录取）',
    domain: 'META',
    mastery: 'Case studied',
    summary: 'Women had a lower aggregate admission rate, but their applications were concentrated in more selective departments; conditioning on the decision unit changed the denominator and the observed relationship.',
    connections: ['META.PROBABILITY.CONDITIONAL'],
  },
  {
    id: 'CASE.AF447.SEARCH.2009_2011',
    label: 'AF447 Bayesian Search（AF447 贝叶斯搜索）',
    domain: 'META',
    mastery: 'Case studied',
    summary: 'Prior location probabilities were updated by search-specific detection probabilities, so failed high-POD searches reduced an area more than failed low-POD searches without automatically eliminating it.',
    connections: ['META.BAYESIAN.UPDATING'],
  },
  {
    id: 'CASE.CDC.ACIP.MRNA_BENEFIT_RISK.2021',
    label: 'ACIP Benefit-Risk 2021（疫苗收益风险）',
    domain: 'META',
    mastery: 'Case studied',
    summary: 'A 120-day per-million-dose model exposed how incidence, effectiveness, age-specific severe outcomes and myocarditis risk jointly shaped an updateable decision rather than a timeless prescription.',
    connections: ['META.PROBABILITY.EXPECTED_VALUE'],
  },
  {
    id: 'CASE.AUTOMOTIVE_SEMICONDUCTOR_SHORTAGE.2020_2022',
    label: 'Automotive Chip Shortage（汽车缺芯）',
    domain: 'META',
    mastery: 'Case studied',
    summary: 'A missing qualified chip blocked complete vehicles while depleted buffers, constrained wafer capacity, multi-tier signals, and production delays turned a component shortage into an industry-wide output constraint.',
    connections: ['META.SYSTEMS.INTEGRATION'],
  },
  {
    id: 'CASE.MONTREAL_PROTOCOL.OZONE_RECOVERY',
    label: 'Ozone Recovery（臭氧层延迟恢复）',
    domain: 'META',
    mastery: 'Case studied',
    summary: 'ODS emissions fell first, effective stratospheric chlorine peaked nearly a decade later, and ozone recovery takes decades because long-lived atmospheric stocks and transport preserve past inputs.',
    connections: ['META.SYSTEMS.DELAY'],
  },
  {
    id: 'CASE.TESLA.MODEL3_RAMP.2017_2018',
    label: 'Model 3 Ramp（Model 3 产能爬坡）',
    domain: 'META',
    mastery: 'Case studied',
    summary: 'Battery module assembly limited complete-vehicle flow despite faster local subsystems; after production improved, the constraint moved toward assembly and delivery logistics.',
    connections: ['META.SYSTEMS.BOTTLENECK'],
  },
  {
    id: 'CASE.CHALLENGER.1986',
    label: 'Challenger STS-51L（挑战者号事故）',
    domain: 'META',
    mastery: 'Case studied',
    summary: 'Cold slowed O-ring recovery while the booster field joint opened during ignition, turning a dynamic sealing margin into a failed pressure boundary.',
    connections: ['META.SYSTEMS.NONLINEARITY'],
  },
  {
    id: 'CASE.SVB.2023_BANK_RUN',
    label: 'SVB 2023 Bank Run（硅谷银行挤兑）',
    domain: 'META',
    mastery: 'Case studied',
    summary: 'Concern drove uninsured deposit withdrawals; withdrawals reduced liquidity and exposed distress; visible distress returned as stronger concern.',
    connections: ['META.SYSTEMS.FEEDBACK_LOOP'],
  },
  {
    id: 'CASE.NORTHEAST_BLACKOUT.2003',
    label: '2003 Northeast Blackout（北美东北部大停电）',
    domain: 'META',
    mastery: 'Case studied',
    summary: 'Line outages redistributed power onto remaining paths while operators lost situational awareness, allowing a local Ohio disturbance to become a regional cascade.',
    connections: ['META.SYSTEMS.COUPLING'],
  },
  {
    id: 'CASE.SOUTHWEST.2022_MELTDOWN',
    label: 'Southwest 2022（西南航空运营崩溃）',
    domain: 'META',
    mastery: 'Case studied',
    summary: 'A healthy aircraft and a legal crew can still be unusable when they are in different cities; the 2022 disruption exposed system capability living in their coordination.',
    connections: ['META.SYSTEMS.INTERDEPENDENCE'],
  },
  {
    id: 'BUS.MEDIA.PAYTV.VALUE_CHAIN',
    label: 'Pay-TV Value Chain（付费电视价值链）',
    domain: 'BUSINESS',
    mastery: 'L1 candidate',
    summary: 'Consumers, distributors, programmers, rights holders, advertisers, and platforms exchange content, access, money, attention, and customer relationships.',
    connections: ['META.SYSTEMS.INTERDEPENDENCE', 'BUS.MEDIA.DISTRIBUTOR.DIRECTV', 'BUS.MEDIA.AGGREGATOR', 'BUS.SUBSCRIPTION.BUNDLE', 'BUS.MEDIA.CORD_CUTTING.SYSTEM_EFFECT', 'BUS.MEDIA.DTC.CUSTOMER_RELATIONSHIP'],
  },
  {
    id: 'BUS.MEDIA.DISTRIBUTOR.DIRECTV',
    label: 'DIRECTV（分发与聚合）',
    domain: 'BUSINESS',
    mastery: 'L1 candidate',
    summary: 'DIRECTV controls customer, billing, package, service, and product relationships while licensing most external content and coordinating third-party networks and apps.',
    connections: ['BUS.MEDIA.PAYTV.VALUE_CHAIN', 'BUS.MEDIA.AGGREGATOR', 'BUS.SUBSCRIPTION.BUNDLE', 'BUS.MEDIA.CORD_CUTTING.SYSTEM_EFFECT', 'BUS.MEDIA.DTC.CUSTOMER_RELATIONSHIP', 'META.SYSTEMS.COUPLING'],
  },
  {
    id: 'BUS.MEDIA.AGGREGATOR',
    label: 'Aggregator（聚合平台）',
    domain: 'BUSINESS',
    mastery: 'L1 candidate',
    summary: 'A platform that reduces search, billing, identity, and discovery friction across fragmented media services.',
    connections: ['META.SYSTEMS.SYSTEM', 'BUS.MEDIA.DISTRIBUTOR.DIRECTV', 'BUS.SUBSCRIPTION.BUNDLE', 'BUS.MEDIA.DTC.CUSTOMER_RELATIONSHIP'],
  },
  {
    id: 'BUS.SUBSCRIPTION.BUNDLE',
    label: 'Bundle（捆绑）',
    domain: 'BUSINESS',
    mastery: 'L1 candidate',
    summary: 'A broad package can smooth heterogeneous household valuations and combine search, contracting, delivery, billing, service, and content funding into one recurring product.',
    connections: ['META.SYSTEMS.SYSTEM', 'META.SYSTEMS.FEEDBACK_LOOP', 'BUS.MEDIA.PAYTV.VALUE_CHAIN', 'BUS.MEDIA.DISTRIBUTOR.DIRECTV', 'BUS.MEDIA.AGGREGATOR', 'BUS.MEDIA.ESPN.BUNDLE_POWER', 'BUS.MEDIA.CORD_CUTTING.SYSTEM_EFFECT', 'BUS.MEDIA.DTC.CUSTOMER_RELATIONSHIP', 'BUS.SUBSCRIPTION.PRICING_PACKAGING'],
  },
  {
    id: 'BUS.MEDIA.ESPN.BUNDLE_POWER',
    label: 'ESPN Bundle Power（ESPN 套餐议价权）',
    domain: 'BUSINESS',
    mastery: 'L1 candidate',
    summary: 'Receiving-subscriber fees and scarce live sports let ESPN seek broad carriage, so non-viewing households indirectly entered the bundle cost base.',
    connections: ['BUS.MEDIA.PAYTV.VALUE_CHAIN', 'BUS.MEDIA.DISTRIBUTOR.DIRECTV', 'BUS.SUBSCRIPTION.BUNDLE', 'META.SYSTEMS.NONLINEARITY', 'BUS.MEDIA.CORD_CUTTING.SYSTEM_EFFECT', 'BUS.MEDIA.INDUSTRY_POWER_SHIFT'],
  },
  {
    id: 'BUS.MEDIA.CORD_CUTTING.SYSTEM_EFFECT',
    label: 'Cord Cutting（剪线退订）',
    domain: 'BUSINESS',
    mastery: 'L1 candidate',
    summary: 'Canceling traditional multichannel Pay-TV removes a recurring payer from the affiliate-fee, advertising-reach, and shared-cost system while video consumption moves elsewhere.',
    connections: ['BUS.MEDIA.PAYTV.VALUE_CHAIN', 'BUS.MEDIA.DISTRIBUTOR.DIRECTV', 'BUS.SUBSCRIPTION.BUNDLE', 'BUS.MEDIA.ESPN.BUNDLE_POWER', 'BUS.MEDIA.DTC.CUSTOMER_RELATIONSHIP', 'META.SYSTEMS.FEEDBACK_LOOP', 'META.SYSTEMS.BOTTLENECK'],
  },
  {
    id: 'BUS.MEDIA.DTC.CUSTOMER_RELATIONSHIP',
    label: 'DTC Customer Relationship（DTC 客户关系）',
    domain: 'BUSINESS',
    mastery: 'L1 candidate',
    summary: 'DTC moves pricing, account, billing, product data, service, and cancellation capabilities toward the programmer, while platform and wholesale paths can still divide the relationship.',
    connections: ['BUS.MEDIA.PAYTV.VALUE_CHAIN', 'BUS.MEDIA.DISTRIBUTOR.DIRECTV', 'BUS.MEDIA.AGGREGATOR', 'BUS.SUBSCRIPTION.BUNDLE', 'BUS.MEDIA.CORD_CUTTING.SYSTEM_EFFECT', 'BUS.MEDIA.DISTRIBUTION.MODELS', 'CASE.DISNEY_PLUS.DTC_2019_2025'],
  },
  {
    id: 'BUS.MEDIA.DISTRIBUTION.MODELS',
    label: 'Video Distribution Models（视频分发模式）',
    domain: 'BUSINESS',
    mastery: 'L1 candidate',
    summary: 'Cable, satellite, vMVPD, and SVOD allocate the access network, content package, bill, product data, and customer relationship differently; streaming alone describes internet delivery.',
    connections: ['BUS.MEDIA.PAYTV.VALUE_CHAIN', 'BUS.MEDIA.DISTRIBUTOR.DIRECTV', 'BUS.MEDIA.DTC.CUSTOMER_RELATIONSHIP', 'BUS.MEDIA.CORD_CUTTING.SYSTEM_EFFECT', 'BUS.MEDIA.STREAMING.TECH_FOUNDATIONS'],
  },
  {
    id: 'BUS.MEDIA.STREAMING.TECH_FOUNDATIONS',
    label: 'Streaming Delivery（流媒体交付）',
    domain: 'BUSINESS',
    mastery: 'L1 candidate',
    summary: 'Encoded segments move through manifests, CDNs, interconnection, ISP access, home networks, devices, buffers, and adaptive bitrate logic; plan Mbps describes only one link.',
    connections: ['BUS.MEDIA.DISTRIBUTION.MODELS', 'BUS.MEDIA.DTC.CUSTOMER_RELATIONSHIP', 'BUS.MEDIA.INDUSTRY_POWER_SHIFT', 'CASE.NETFLIX.OPEN_CONNECT'],
  },
  {
    id: 'BUS.MEDIA.INDUSTRY_POWER_SHIFT',
    label: 'Industry Power Shift（行业权力转移）',
    domain: 'BUSINESS',
    mastery: 'L1 candidate',
    summary: 'Media bargaining power depends on outside options, no-deal costs, time sensitivity, and control of scarce content, customer access, broadband, billing, packaging, data, and discovery.',
    connections: ['BUS.MEDIA.ESPN.BUNDLE_POWER', 'BUS.MEDIA.CORD_CUTTING.SYSTEM_EFFECT', 'BUS.MEDIA.DTC.CUSTOMER_RELATIONSHIP', 'BUS.MEDIA.DISTRIBUTION.MODELS', 'BUS.MEDIA.STREAMING.TECH_FOUNDATIONS', 'BUS.SUBSCRIPTION.ECONOMICS.FOUNDATION', 'CASE.CHARTER.DISNEY.DISTRIBUTION.2023_2025'],
  },
  {
    id: 'BUS.SUBSCRIPTION.ECONOMICS.FOUNDATION',
    label: 'Subscription Economics（订阅经济基础）',
    domain: 'BUSINESS',
    mastery: 'L1 candidate',
    summary: 'A subscription is a continuing payer relationship: additions and cancellations change the customer stock, while customer-months, realized prices and plan mix generate period revenue.',
    connections: ['BUS.SUBSCRIPTION.BUNDLE', 'BUS.MEDIA.CORD_CUTTING.SYSTEM_EFFECT', 'BUS.MEDIA.DTC.CUSTOMER_RELATIONSHIP', 'BUS.MEDIA.INDUSTRY_POWER_SHIFT', 'BUS.SUBSCRIPTION.CHURN_RETENTION', 'BUS.SUBSCRIPTION.CAC_PAYBACK', 'BUS.SUBSCRIPTION.LTV', 'BUS.SUBSCRIPTION.PRICING_PACKAGING', 'CASE.NETFLIX.PRICING.2011'],
  },
  {
    id: 'BUS.SUBSCRIPTION.CHURN_RETENTION',
    label: 'Churn & Retention（流失与留存）',
    domain: 'BUSINESS',
    mastery: 'L1 candidate',
    summary: 'Churn requires an explicit exit, denominator and period; cohort retention follows the same relationships through tenure so changing acquisition, plan and exit mix cannot hide inside one aggregate rate.',
    connections: ['BUS.SUBSCRIPTION.ECONOMICS.FOUNDATION', 'BUS.SUBSCRIPTION.CAC_PAYBACK', 'BUS.SUBSCRIPTION.LTV', 'BUS.SUBSCRIPTION.PRICING_PACKAGING', 'META.CAUSAL.SELECTION_BIAS', 'CASE.NETFLIX.PRICING.2011'],
  },
  {
    id: 'BUS.SUBSCRIPTION.CAC_PAYBACK',
    label: 'CAC & Payback（获客成本与回收期）',
    domain: 'BUSINESS',
    mastery: 'L1 candidate',
    summary: 'Acquisition spending is recovered by retained cohort contribution margin, not ARPU; payback accumulates active customer-month margin until it covers consistently defined CAC or SAC.',
    connections: ['BUS.SUBSCRIPTION.ECONOMICS.FOUNDATION', 'BUS.SUBSCRIPTION.CHURN_RETENTION', 'BUS.SUBSCRIPTION.LTV', 'CASE.DIRECTV.SAC_PAYBACK.2014'],
  },
  {
    id: 'BUS.SUBSCRIPTION.LTV',
    label: 'LTV & Unit Economics（终身价值与单位经济）',
    domain: 'BUSINESS',
    mastery: 'L1 candidate',
    summary: 'LTV is the present value of future cohort contribution margin, built from retention, realized margin and discounting; acquisition value requires comparison with consistently scoped CAC or SAC.',
    connections: ['BUS.SUBSCRIPTION.ECONOMICS.FOUNDATION', 'BUS.SUBSCRIPTION.CHURN_RETENTION', 'BUS.SUBSCRIPTION.CAC_PAYBACK', 'BUS.SUBSCRIPTION.PRICING_PACKAGING', 'BUS.MEDIA.AD_SUPPORTED_STREAMING', 'META.PROBABILITY.FOUNDATION', 'META.PROBABILITY.EXPECTED_VALUE', 'CASE.DIRECTV.LTV_PROXY.2014'],
  },
  {
    id: 'BUS.SUBSCRIPTION.PRICING_PACKAGING',
    label: 'Pricing & Packaging（定价与套餐）',
    domain: 'BUSINESS',
    mastery: 'L1 candidate',
    summary: 'Pricing sets exchange terms; packaging combines content, features, advertising and products into tiers whose migration, retention and contribution determine value beyond list price.',
    connections: ['BUS.SUBSCRIPTION.ECONOMICS.FOUNDATION', 'BUS.SUBSCRIPTION.CHURN_RETENTION', 'BUS.SUBSCRIPTION.LTV', 'BUS.MEDIA.AD_SUPPORTED_STREAMING', 'BUS.SUBSCRIPTION.BUNDLE', 'CASE.DISNEY_PLUS.TIERING.2022_2023'],
  },
  {
    id: 'BUS.MEDIA.AD_SUPPORTED_STREAMING',
    label: 'Ad-Supported Streaming（广告支持流媒体）',
    domain: 'BUSINESS',
    mastery: 'L1 candidate',
    summary: 'Viewer-hours create limited advertising inventory; subscription plus ad revenue must be evaluated after fill, net CPM, rights, ad costs, migration and retention rather than from the lower subscription price alone.',
    connections: ['BUS.SUBSCRIPTION.PRICING_PACKAGING', 'BUS.SUBSCRIPTION.CHURN_RETENTION', 'BUS.SUBSCRIPTION.LTV', 'BUS.MEDIA.STREAMING.TECH_FOUNDATIONS', 'BUS.MEDIA.DTC.CUSTOMER_RELATIONSHIP', 'BUS.MEDIA.REAGGREGATION', 'META.PROBABILITY.CONDITIONAL', 'CASE.NETFLIX.AD_SUPPORTED_PLAN.2022_2024'],
  },
  {
    id: 'BUS.MEDIA.REAGGREGATION',
    label: 'Streaming Re-aggregation（流媒体再聚合）',
    domain: 'BUSINESS',
    mastery: 'L1 candidate',
    summary: 'Independent streaming services can recombine pricing, billing, entitlement, discovery and device placement while retaining separate apps, brands, rights and parts of the customer relationship.',
    connections: ['BUS.SUBSCRIPTION.BUNDLE', 'BUS.MEDIA.DTC.CUSTOMER_RELATIONSHIP', 'BUS.SUBSCRIPTION.PRICING_PACKAGING', 'BUS.SUBSCRIPTION.CHURN_RETENTION', 'BUS.SUBSCRIPTION.LTV', 'BUS.MEDIA.AD_SUPPORTED_STREAMING', 'BUS.MEDIA.DEVICE_OS_POWER', 'META.BAYESIAN.UPDATING', 'CASE.COMCAST.STREAMSAVER.2024'],
  },
  {
    id: 'BUS.MEDIA.DEVICE_OS_POWER',
    label: 'Device & OS Power（设备与操作系统权力）',
    domain: 'BUSINESS',
    mastery: 'L1 candidate',
    summary: 'The TV OS controls repeated pre-viewing surfaces such as the home screen, cross-app discovery, identity, optional billing, advertising and data, creating distribution power without owning most content or broadband.',
    connections: ['BUS.MEDIA.DISTRIBUTION.MODELS', 'BUS.MEDIA.STREAMING.TECH_FOUNDATIONS', 'BUS.MEDIA.DTC.CUSTOMER_RELATIONSHIP', 'BUS.MEDIA.REAGGREGATION', 'BUS.MEDIA.AD_SUPPORTED_STREAMING', 'BUS.MEDIA.APP_DISTRIBUTION_TERMS', 'META.PROBABILITY.EXPECTED_VALUE', 'CASE.ROKU.DEVICE_OS_POWER.2024'],
  },
  {
    id: 'CASE.NETFLIX.OPEN_CONNECT',
    label: 'Netflix Open Connect（本地内容交付）',
    domain: 'BUSINESS',
    mastery: 'Case studied',
    summary: 'Netflix places encoded content near or inside ISP networks to reduce repeated long-haul delivery while preserving separate video-service and broadband relationships.',
    connections: ['BUS.MEDIA.STREAMING.TECH_FOUNDATIONS'],
  },
  {
    id: 'CASE.CHARTER.DISNEY.DISTRIBUTION.2023_2025',
    label: 'Charter–Disney 2023–25（分发协议）',
    domain: 'BUSINESS',
    mastery: 'Case studied',
    summary: 'A blackout made each side\'s fallback costs visible; successive agreements traded core networks, package flexibility, wholesale streaming entitlements, broadband distribution, and advertising reach.',
    connections: ['BUS.MEDIA.INDUSTRY_POWER_SHIFT'],
  },
  {
    id: 'CASE.DISNEY_PLUS.DTC_2019_2025',
    label: 'Disney+ DTC（Disney+ 直面消费者）',
    domain: 'BUSINESS',
    mastery: 'Case studied',
    summary: 'Disney gained direct product and customer capabilities while taking on technology, marketing, service, content, and churn; partner billing still divided parts of the relationship.',
    connections: ['BUS.MEDIA.DTC.CUSTOMER_RELATIONSHIP'],
  },
  {
    id: 'CASE.NETFLIX.PRICING.2011',
    label: 'Netflix Pricing 2011（订阅关系冲击）',
    domain: 'BUSINESS',
    mastery: 'Case studied',
    summary: 'Gross additions remained large, but cancellations were larger; reported churn rose to 6.3%, while customer-month timing, price, plan and cohort mix shaped revenue and the ending subscriber stock.',
    connections: ['BUS.SUBSCRIPTION.ECONOMICS.FOUNDATION', 'BUS.SUBSCRIPTION.CHURN_RETENTION'],
  },
  {
    id: 'CASE.DIRECTV.SAC_PAYBACK.2014',
    label: 'DIRECTV SAC 2014（订户获取经济）',
    domain: 'BUSINESS',
    mastery: 'Case studied',
    summary: 'DIRECTV reported $883 SAC; ARPU implied a false 8.3-month recovery, while contribution margin and retained cohort customer-months made the economic payback much longer.',
    connections: ['BUS.SUBSCRIPTION.CAC_PAYBACK'],
  },
  {
    id: 'CASE.DIRECTV.LTV_PROXY.2014',
    label: 'DIRECTV LTV Proxy 2014（终身价值代理）',
    domain: 'BUSINESS',
    mastery: 'Case studied',
    summary: 'Public segment averages illustrate how retention, contribution and discounting shape LTV, while their mixed-cohort boundaries prevent the proxy from becoming an official customer-level result.',
    connections: ['BUS.SUBSCRIPTION.LTV'],
  },
  {
    id: 'CASE.DISNEY_PLUS.TIERING.2022_2023',
    label: 'Disney+ Tiering 2022–23（分层定价）',
    domain: 'BUSINESS',
    mastery: 'Case studied',
    summary: 'Disney+ preserved a $7.99 ad-supported entry tier and raised ad-free to $10.99, combining subscription pricing, advertiser revenue and bundle mix without revealing plan-level retention.',
    connections: ['BUS.SUBSCRIPTION.PRICING_PACKAGING'],
  },
  {
    id: 'CASE.NETFLIX.AD_SUPPORTED_PLAN.2022_2024',
    label: 'Netflix Ads 2022–24（Netflix 广告档）',
    domain: 'BUSINESS',
    mastery: 'Case studied',
    summary: 'Netflix launched a $6.99 ad tier with four to five ad minutes per hour and scaled reported global MAU from nearly 5 million to 40 million, without disclosing plan-level contribution or LTV.',
    connections: ['BUS.MEDIA.AD_SUPPORTED_STREAMING'],
  },
  {
    id: 'CASE.COMCAST.STREAMSAVER.2024',
    label: 'Comcast StreamSaver 2024（流媒体再聚合）',
    domain: 'BUSINESS',
    mastery: 'Case studied',
    summary: 'A $15 Xfinity bundle recombined Netflix, Peacock and Apple TV+ pricing, billing and entitlements while the services remained distinct apps and undisclosed wholesale economics limited value conclusions.',
    connections: ['BUS.MEDIA.REAGGREGATION'],
  },
  {
    id: 'CASE.ROKU.DEVICE_OS_POWER.2024',
    label: 'Roku OS Power 2024（Roku 平台权力）',
    domain: 'BUSINESS',
    mastery: 'Case studied',
    summary: 'Roku paired low- or negative-margin device economics with a much larger profitable platform layer built on home-screen discovery, advertising, billing and distribution relationships.',
    connections: ['BUS.MEDIA.DEVICE_OS_POWER'],
  },
]

export const todayBrief = {
  date: '2026-09-24',
  title: 'Expected Value（期望值）',
  question: '如果一项行动有少量严重副作用，为什么它仍可能拥有更高的概率加权价值？',
  reading: '45-60 min：沿 ACIP 每一百万第二剂的决策单位，拆开概率、结果层级、价值与敏感假设。',
  discussion: '20-30 min：计算工厂安全投资的期望成本，并沿一名观众拆解 Roku OS 权力。',
  next: '2026-09-25：Anchoring 与 App Distribution / Platform Terms。',
}

export const monthlyTrack = [
  'Systems Thinking（系统思维）',
  'Causal Reasoning（因果推理）',
  'Probability（概率）',
  'Bayesian Thinking（贝叶斯思维）',
  'Source Evaluation（信息源评估）',
  'Forecasting（预测）',
]
